### ISSUE TITLE
Add loging of all requests and responses

### ISSUE THREAD

**Issue by robinvanderknaap** [robinvanderknaap/iDeal.NET#1]
All requests and responses should be logged. It should be possible to inject own choice of logging framework.

**Comment by aminahmad49** [comment]
Hi Robin,

I am doing integration with ideal-rabobank. Using C# . Below is my code 

var directoryRequestXmlMessage =
                new XDocument(
                    new XDeclaration("1.0", "UTF-8", null),
                    new XElement(xmlNamespace + "DirectoryReq",
                        new XAttribute("version", "1.1.0"),
                        new XElement(xmlNamespace + "createDateTimeStamp", CreateDateTimeStamp),
                        new XElement(xmlNamespace + "Merchant",
                            new XElement(xmlNamespace + "merchantID", MerchantId.PadLeft(9, '0')),
                            new XElement(xmlNamespace + "subID", MerchantSubId),
                            new XElement(xmlNamespace + "authentication", "SHA1_RSA"),
                          new XElement(xmlNamespace + "KeyName", signatureProvider.GetThumbprintAcceptantCertificate()),
                          new XElement(xmlNamespace + "SignatureValue", signatureProvider.GetSignature(CreateDateTimeStamp + MerchantId + MerchantSubId))
                        )
                    )
                );

When I post to this url  https://idealtest.rabobank.nl/ideal/iDEALv3 it throw error. <errorCode>IX1100</errorCode>
<errorMessage>Received XML not valid</errorMessage>. Kindly let guide me how to fix this issue I am struggling with integration from many days.

Kind Regards,
Amin
