### ISSUE TITLE
Bad xml error

### ISSUE THREAD

**Issue by aminahmad49** [robinvanderknaap/iDeal.NET#4]
I am doing integration with ideal-rabobank. Using C# . Below is my code 

var directoryRequestXmlMessage =
                new XDocument(
                    new XDeclaration("1.0", "UTF-8", null),
                    new XElement(xmlNamespace + "DirectoryReq",
                        new XAttribute("version", "1.1.0"),
                        new XElement(xmlNamespace + "createDateTimeStamp", CreateDateTimeStamp),
                        new XElement(xmlNamespace + "Merchant",
                            new XElement(xmlNamespace + "merchantID", MerchantId.PadLeft(9, '0')),
                            new XElement(xmlNamespace + "subID", MerchantSubId),
                            new XElement(xmlNamespace + "authentication", "SHA1_RSA"),
                          new XElement(xmlNamespace + "KeyName", signatureProvider.GetThumbprintAcceptantCertificate()),
                          new XElement(xmlNamespace + "SignatureValue", signatureProvider.GetSignature(CreateDateTimeStamp + MerchantId + MerchantSubId))
                        )
                    )
                );

When I post to this url  https://idealtest.rabobank.nl/ideal/iDEALv3 it throw error. <errorCode>IX1100</errorCode>
<errorMessage>Received XML not valid</errorMessage>. Kindly let guide me how to fix this issue I am struggling with integration from many days.

Kind Regards,
Amin

**Comment by Courta** [comment]
Sorry, this library is out of date, the specs of iDeal have been changed since the release of this library. So basically it's useless now.

**Comment by aminahmad49** [comment]
Hi Courta,

Can you please guide me how to integrate with Rabo Bank -Ideal Uisng C#. ?

Regard,
Amin

**Comment by robinvanderknaap** [comment]
No, the specs have changed, and I haven't done an implementation after that. (I'm Courta by the way).

**Comment by aminahmad49** [comment]
Hi Courta ,

You added nugget package on https://www.nuget.org/packages/iDeal.NET/. So all nugget package in useless right?

Regards,
Amin

**Comment by robinvanderknaap** [comment]
right

**Comment by aminahmad49** [comment]
Hi Courta ,

I will appreciate you if  guide me how to generate electronic signature in C# for Ideal payments. Everything is OK now I getting this error "Invalid electronic signature". 

Kind Regards,
Amin

**Comment by bartvanderwal** [comment]
Hi Courta, Robin,
Could you mention that this library should no longer be used in the README.md. I just spent a couple of hours setting things up, since this was the only iDeal package in the whole of nuget. But now reading this comment it seems those hours were wasted. I'd like to save other developers from this.

I could do a pull request myself with a change in README.md if you want.

**Comment by bartvanderwal** [comment]
@Courta @robinvanderknaap I thought I'dd @mention you as well, in case this helps. See my comment above.

**Comment by robinvanderknaap** [comment]
@bartvanderwal Hi Bart, sorry for the inconvenience, i've updated the readme.md

**Comment by bartvanderwal** [comment]
Brilliant, thanks for the update!
